### ISSUE TITLE
Effects doesn't work on rxjs 5.4.2

### ISSUE THREAD

**Issue by ritox842** [ngrx/effects#165]
I can't use effects middleware on this version.
Rxjs changed their type of lift.

If anyone facing it you can resolve it by going to effect's actions.d.ts and change 

`  lift(operator: Operator<any, Action>): Observable<Action>;`

to

`  lift<R>(operator: Operator<Action, R>): Observable<R>`

**Comment by jeffwhelpley** [comment]
Yep. I get the following error:

```
ERROR in /Users/jeffwhelpley/repos/app-backstage/node_modules/@ngrx/effects/src/actions.d.ts (4,22): Class 'Actions' incorrectly extends base class 'Observable<Action>'.
  Types of property 'lift' are incompatible.
    Type '(operator: Operator<any, Action>) => Observable<Action>' is not assignable to type '<R>(operator: Operator<Action, R>) => Observable<R>'.
      Types of parameters 'operator' and 'operator' are incompatible.
        Type 'Operator<Action, R>' is not assignable to type 'Operator<any, Action>'.
          Type 'R' is not assignable to type 'Action'.
```

**Comment by jeffwhelpley** [comment]
I tried to clone the repo and make the fix, but when I `tsc` I get this error:

```
src/actions.ts(19,5): error TS90010: Type 'Operator<any, Action>' is not assignable to type 'Operator<any, Action>'. Two different types with this name exist, but they are unrelated.
  Type 'Action' is not assignable to type 'Action'. Two different types with this name exist, but they are unrelated.
src/actions.ts(20,5): error TS2322: Type 'Actions' is not assignable to type 'Observable<Action>'.
  Types of property 'operator' are incompatible.
    Type 'Operator<any, Action>' is not assignable to type 'Operator<any, Action>'. Two different types with this name exist, but they are unrelated.
      Type 'Action' is not assignable to type 'Action'. Two different types with this name exist, but they are unrelated.
```

I will look more in this later today.

**Comment by ritox842** [comment]
@jeffwhelpley  did you changed the actions.d.ts file as I said ? It worked for me..

**Comment by pfrendo** [comment]
https://github.com/ngrx/effects/pull/166

**Comment by jeffwhelpley** [comment]
@pfrendo for your PR did you `tsc`? When I do that, I get an error, but perhaps there is something messed up with my local clone. Also, once that is working, I believe you have to run `npm build` and perhaps more to get all the generated files.

**Comment by jeffwhelpley** [comment]
@ritox842 just changing actions.d.ts is not enough. That is a generated file. We need to update the actions.ts and then generate the distributable code.

**Comment by marvi14** [comment]
When will this be merged?

**Comment by ritox842** [comment]
@jeffwhelpley  

Of course, It's a temporary solution

**Comment by brandonroberts** [comment]
Closed via #167 and published as `2.0.4`
